spring:
  application:
    name: api-gateway

server:
  port: 1101

zuul:
  routes:
#  single-instance
#    eureka-client:
#      path: /eureka-client/**
#      url: http://localhost:2001/
#  multi-instance
    eureka-client:
      path: /eureka-client/**
      serviceId: api-b

api-b:
  ribbon:
    listOfServers: http://localhost:2001/, http://localhost:2002/